/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.src.frugalinnovationlab.view;

import com.src.frugalinnovationlab.Controller.AddNewProjectController;
import com.src.frugalinnovationlab.Entity.Filetypes;
import com.src.frugalinnovationlab.Entity.MediaAdobe;
import com.src.frugalinnovationlab.Entity.MediaAdobePK;
import com.src.frugalinnovationlab.Entity.MediaCad;
import com.src.frugalinnovationlab.Entity.MediaCode;
import com.src.frugalinnovationlab.Entity.MediaHyperlink;
import com.src.frugalinnovationlab.Entity.MediaPdf;
import com.src.frugalinnovationlab.Entity.MediaPhotos;
import com.src.frugalinnovationlab.Entity.MediaPlaintext;
import com.src.frugalinnovationlab.Entity.MediaSpreadsheet;
import com.src.frugalinnovationlab.Entity.MediaVideo;
import com.src.frugalinnovationlab.Entity.MediaWord;
import com.src.frugalinnovationlab.Entity.ParticipantDesignation;
import com.src.frugalinnovationlab.Entity.Participants;
import com.src.frugalinnovationlab.Entity.ProjectCategory;
import com.src.frugalinnovationlab.Entity.ProjectStatus;
import com.src.frugalinnovationlab.Entity.Projectfiles;
import com.src.frugalinnovationlab.Entity.Tags;
import com.src.frugalinnovationlab.Wrappers.AssignParticipantsToProject;
import java.sql.Array;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import com.src.frugalinnovationlab.Wrappers.ComboItem;
import com.src.frugalinnovationlab.helper.EmailFormatValidator;
import com.src.frugalinnovationlab.helper.PhoneNumberValidator;
import java.io.File;
import java.util.Collections;
import java.util.Comparator;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFileChooser;
import javax.swing.JList;

/**
 *
 * @author diptik
 */
public class AddNewProjectPanel extends javax.swing.JPanel {

    AddNewProjectController addNewProjectController;
    List<ProjectStatus> projectStatusList;
    List<ProjectCategory> projectCategoryList;
    ArrayList categorySelected = new ArrayList();
    List<ParticipantDesignation> participantDesignationsList;
    List<Participants> participants;
    List<Tags> tagsList;
    DefaultTableModel model1 = new DefaultTableModel();
    List<String> categoriesList;
    DefaultTableModel model = new DefaultTableModel();
    ArrayList<AssignParticipantsToProject> participantsList = new ArrayList<AssignParticipantsToProject>();
    List<MediaAdobe> adobeFileList = new ArrayList<MediaAdobe>();
    List<MediaCad> cadFileList = new ArrayList<MediaCad>();
    List<MediaCode> codeFileList = new ArrayList<MediaCode>();
    List<MediaHyperlink> hyperLinkList = new ArrayList<MediaHyperlink>();
    List<MediaPdf> pdfList = new ArrayList<MediaPdf>();
    List<MediaPhotos> photosList = new ArrayList<MediaPhotos>();
    List<MediaPlaintext> plainTextList = new ArrayList<MediaPlaintext>();
    List<MediaSpreadsheet> spreadSheetList = new ArrayList<MediaSpreadsheet>();
    List<MediaVideo> videoList = new ArrayList<MediaVideo>();
    List<MediaWord> wordList = new ArrayList<MediaWord>();
    List<String> selectedTagsList;
    List<Filetypes> fileTypeList;
    List<Projectfiles> filesList = new ArrayList<Projectfiles>();


    /**
     * Creates new form AddNewProjectPanel
     */
    public AddNewProjectPanel() {
        addNewProjectController = new AddNewProjectController(this);
        projectStatusList = addNewProjectController.getProjectStatusFromDatabase();
        categoriesList = new ArrayList<String>();
        projectCategoryList = addNewProjectController.getProjectCategoriesFromDatabase();
        participantDesignationsList = addNewProjectController.getParticipantsDesignationFromDatabase();
        participants = addNewProjectController.getParticipantsFromDatabase();
        tagsList = addNewProjectController.getTagsFromDatabase();
        fileTypeList = addNewProjectController.fetchFileTypes();
        initComponents();
        newTagsLabelField.setVisible(false);
        newTagsTextField.setVisible(false);
        addParticipantPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createProjectPane = new javax.swing.JTabbedPane();
        generalinfoScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        addNewProjectTextArea = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        shortDescriptionTextField = new javax.swing.JTextField();
        projectNameLabel = new javax.swing.JLabel();
        shortDescriptionLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        generalProjectInfoLabel = new javax.swing.JLabel();
        statusProjectLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        bioengineeringCheckBox = new javax.swing.JCheckBox();
        computerEngineeringCheckBox = new javax.swing.JCheckBox();
        civilEngineeringCheckBox = new javax.swing.JCheckBox();
        mechanicalEngineeringCheckBox = new javax.swing.JCheckBox();
        electricalEngineeringCheckBox = new javax.swing.JCheckBox();
        locationLabel = new javax.swing.JLabel();
        projectLocationTextField = new javax.swing.JTextField();
        projectStatusComboBox = new javax.swing.JComboBox();
        startDateLabel = new javax.swing.JLabel();
        startDate = new com.toedter.calendar.JDateChooser();
        endDate = new com.toedter.calendar.JDateChooser();
        scopeLabel = new javax.swing.JLabel();
        scopeTextField = new javax.swing.JTextField();
        outcomeLabel = new javax.swing.JLabel();
        outcomeTextField = new javax.swing.JTextField();
        projectIdTextField = new javax.swing.JTextField();
        moveToParticipants = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoLabel2 = new javax.swing.JLabel();
        logoLabel6 = new javax.swing.JLabel();
        tagsOptionsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectTagsOptions = new javax.swing.JList();
        addNewTags = new javax.swing.JRadioButton();
        newTagsLabelField = new javax.swing.JLabel();
        newTagsTextField = new javax.swing.JTextField();
        participantsScrollPane = new javax.swing.JScrollPane();
        mainPanel3 = new javax.swing.JPanel();
        addNewProjectTextArea3 = new javax.swing.JLabel();
        participantRoleLabel = new javax.swing.JLabel();
        generalProjectInfoLabel3 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        roleComboBox = new javax.swing.JComboBox();
        participantNameLabel = new javax.swing.JLabel();
        chooseParticipantComboBox = new javax.swing.JComboBox();
        addParticipantButton = new javax.swing.JButton();
        listProjectParticipantsLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteParticipantButton = new javax.swing.JButton();
        addParticipantButton1 = new javax.swing.JButton();
        addNewParticipantButton = new javax.swing.JButton();
        addParticipantPanel = new javax.swing.JPanel();
        addTitleComboBox = new javax.swing.JComboBox();
        addTitleLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        designationLabel = new javax.swing.JLabel();
        designationTextField = new javax.swing.JTextField();
        addNewParticipantPanelButton = new javax.swing.JButton();
        addNewParticipantRoleComboBox = new javax.swing.JComboBox();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phoneLabel = new javax.swing.JLabel();
        phoneTextField = new javax.swing.JTextField();
        organizationLabel = new javax.swing.JLabel();
        organizationTextField = new javax.swing.JTextField();
        addTitleLabel1 = new javax.swing.JLabel();
        multimediaScrollPane = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        addAdobeTextField = new javax.swing.JTextField();
        addProjectButton3 = new javax.swing.JButton();
        adobeFilesLabel1 = new javax.swing.JLabel();
        addNewProjectTextArea2 = new javax.swing.JLabel();
        addadobefileButton = new javax.swing.JButton();
        fileNameTextField = new javax.swing.JTextField();
        cadDocumentLabel1 = new javax.swing.JLabel();
        generalProjectInfoLabel4 = new javax.swing.JLabel();
        logoLabel4 = new javax.swing.JLabel();
        fileNameLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        addProjectButton = new javax.swing.JButton();
        addNewProjectTextArea4 = new javax.swing.JLabel();
        logoLabel5 = new javax.swing.JLabel();
        generalProjectInfoLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 170, 153), 4));

        createProjectPane.setBackground(new java.awt.Color(255, 255, 255));
        createProjectPane.setForeground(new java.awt.Color(0, 95, 45));
        createProjectPane.setPreferredSize(new java.awt.Dimension(800, 800));
        createProjectPane.setVerifyInputWhenFocusTarget(false);

        generalinfoScrollPane.setBorder(null);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel.setPreferredSize(new java.awt.Dimension(716, 773));

        addNewProjectTextArea.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addNewProjectTextArea.setText("Add New Project");

        projectNameTextField.setColumns(20);
        projectNameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        projectNameTextField.setToolTipText("Enter Project Name");
        projectNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectNameTextFieldActionPerformed(evt);
            }
        });

        shortDescriptionTextField.setColumns(20);
        shortDescriptionTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        shortDescriptionTextField.setToolTipText("Enter Short Description");

        projectNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        projectNameLabel.setText("Project Name");
        projectNameLabel.setToolTipText("");

        shortDescriptionLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        shortDescriptionLabel.setText("Short Description");
        shortDescriptionLabel.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("General Description");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("Enter Long Description");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        generalProjectInfoLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        generalProjectInfoLabel.setText("Step 1 - General Project Information");

        statusProjectLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        statusProjectLabel.setText("Status of Project");

        categoryLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        categoryLabel.setText("Category");

        bioengineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        bioengineeringCheckBox.setText("Bioengineering");
        bioengineeringCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioengineeringCheckBoxActionPerformed(evt);
            }
        });

        computerEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        computerEngineeringCheckBox.setText("Computer Engineering");
        computerEngineeringCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computerEngineeringCheckBoxActionPerformed(evt);
            }
        });

        civilEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        civilEngineeringCheckBox.setText("Civil Engineering");
        civilEngineeringCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilEngineeringCheckBoxActionPerformed(evt);
            }
        });

        mechanicalEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        mechanicalEngineeringCheckBox.setText("Mechanical Engineering");
        mechanicalEngineeringCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mechanicalEngineeringCheckBoxActionPerformed(evt);
            }
        });

        electricalEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        electricalEngineeringCheckBox.setText("Electrical Engineering");
        electricalEngineeringCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electricalEngineeringCheckBoxActionPerformed(evt);
            }
        });

        locationLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        locationLabel.setText("Location");

        projectLocationTextField.setColumns(20);
        projectLocationTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        projectLocationTextField.setToolTipText("Input a Location");
        projectLocationTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectLocationTextFieldActionPerformed(evt);
            }
        });

        projectStatusComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        projectStatusComboBox.setForeground(new java.awt.Color(0, 95, 45));
        projectStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Status" }));
        Array [] arr = new Array[projectStatusList.size()];
        //System.out.println("arr = " +arr.toString());

        for(int i = 0; i < projectStatusList.size(); i++){
            //projectStatusList.get(i).getStatus();
            projectStatusComboBox.addItem(projectStatusList.get(i).getStatus());
        }
        projectStatusComboBox.setToolTipText("Choose a Status");
        projectStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectStatusComboBoxActionPerformed(evt);
            }
        });

        startDateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        startDateLabel.setText("Start/End Date");

        startDate.setBackground(new java.awt.Color(150, 170, 153));
        startDate.setToolTipText("Choose a Start Date");

        endDate.setBackground(new java.awt.Color(150, 170, 153));
        endDate.setToolTipText("Choose an End Date");

        scopeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        scopeLabel.setText("Scope");

        scopeTextField.setColumns(20);
        scopeTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        scopeTextField.setToolTipText("Scope");
        scopeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scopeTextFieldActionPerformed(evt);
            }
        });

        outcomeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        outcomeLabel.setText("Outcome");

        outcomeTextField.setColumns(20);
        outcomeTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        outcomeTextField.setToolTipText("Outcome");

        projectIdTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        projectIdTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectIdTextFieldActionPerformed(evt);
            }
        });

        moveToParticipants.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        moveToParticipants.setForeground(new java.awt.Color(0, 95, 45));
        moveToParticipants.setText("Next");
        moveToParticipants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveToParticipantsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Project ID");

        logoLabel2.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scu-mission.png"))); // NOI18N

        logoLabel6.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scu-mission.png"))); // NOI18N

        tagsOptionsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        tagsOptionsLabel.setText("Tags");

        String[] tagsArray = new String[tagsList.size()];
        for (int i = 0; i < tagsList.size(); i++) {
            String tagname = tagsList.get(i).getTagname();
            tagsArray[i] = tagname;
        }
        projectTagsOptions = new JList(tagsArray);
        jScrollPane2.setViewportView(projectTagsOptions);

        addNewTags.setText("Add New Tags");
        addNewTags.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewTagsActionPerformed(evt);
            }
        });

        newTagsLabelField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        newTagsLabelField.setText("New Tags");

        newTagsTextField.setColumns(20);
        newTagsTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        newTagsTextField.setToolTipText("Outcome");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewProjectTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generalProjectInfoLabel)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusProjectLabel)
                            .addComponent(categoryLabel)
                            .addComponent(locationLabel)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(scopeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(outcomeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                .addComponent(tagsOptionsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(newTagsLabelField)
                                .addComponent(startDateLabel)))
                        .addGap(38, 38, 38)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(computerEngineeringCheckBox)
                            .addComponent(projectStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(bioengineeringCheckBox)
                                .addGap(42, 42, 42)
                                .addComponent(electricalEngineeringCheckBox))
                            .addComponent(scopeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(shortDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                    .addComponent(civilEngineeringCheckBox)
                                    .addGap(32, 32, 32)
                                    .addComponent(mechanicalEngineeringCheckBox))
                                .addComponent(moveToParticipants))
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(outcomeTextField, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(addNewTags)
                            .addComponent(newTagsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(shortDescriptionLabel)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(projectNameLabel)
                            .addComponent(jLabel1))))
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(243, 243, 243)
                    .addComponent(logoLabel2)
                    .addContainerGap(297, Short.MAX_VALUE)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(243, 243, 243)
                    .addComponent(logoLabel6)
                    .addContainerGap(297, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(addNewProjectTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(generalProjectInfoLabel)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(projectIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shortDescriptionLabel)
                    .addComponent(shortDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusProjectLabel)
                    .addComponent(projectStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryLabel)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(electricalEngineeringCheckBox)
                        .addComponent(bioengineeringCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(civilEngineeringCheckBox)
                    .addComponent(mechanicalEngineeringCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(computerEngineeringCheckBox)
                .addGap(2, 2, 2)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(projectLocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(startDateLabel)
                            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(scopeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scopeLabel)))
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(outcomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outcomeLabel))
                .addGap(31, 31, 31)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tagsOptionsLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNewTags)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newTagsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newTagsLabelField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moveToParticipants)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(logoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(228, Short.MAX_VALUE)))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(logoLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(228, Short.MAX_VALUE)))
        );

        bioengineeringCheckBox.getAccessibleContext().setAccessibleName("Bio Engineering");

        generalinfoScrollPane.setViewportView(mainPanel);

        createProjectPane.addTab("General Details", generalinfoScrollPane);

        participantsScrollPane.setBorder(null);
        participantsScrollPane.setPreferredSize(new java.awt.Dimension(600, 600));

        mainPanel3.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel3.setPreferredSize(new java.awt.Dimension(600, 600));

        addNewProjectTextArea3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addNewProjectTextArea3.setText("Add New Project");

        participantRoleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        participantRoleLabel.setText("Participant Name");

        generalProjectInfoLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        generalProjectInfoLabel3.setText("Step 2 - Project Participants");

        roleComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        roleComboBox.setForeground(new java.awt.Color(0, 95, 45));
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Role" }));
        Array [] roleArray = new Array[participantDesignationsList.size()];
        //System.out.println("arr = " +roleArray.toString());
        //designationComboBox.addItem("Your Choices");
        for(int i = 0; i < participantDesignationsList.size(); i++){
            //System.out.println(participantDesignationsList.get(i).getName());
            roleComboBox.addItem(new ComboItem(participantDesignationsList.get(i).getName(), Integer.toString(participantDesignationsList.get(i).getId())));
        }
        roleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBoxActionPerformed(evt);
            }
        });

        participantNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        participantNameLabel.setText("Participant Role");

        chooseParticipantComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        chooseParticipantComboBox.setForeground(new java.awt.Color(0, 95, 45));
        chooseParticipantComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose A Participant" }));
        this.sortParticipants();
        for(int i = 0; i < participants.size(); i++){
            String fullName = participants.get(i).getNameTitle().concat(" "+
                participants.get(i).getFirstname()).concat(" "+participants.get(i).getLastname());
            chooseParticipantComboBox.addItem(new ComboItem(fullName, Integer.toString(participants.get(i).getId())));
        }
        chooseParticipantComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseParticipantComboBoxActionPerformed(evt);
            }
        });

        addParticipantButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addParticipantButton.setForeground(new java.awt.Color(0, 95, 45));
        addParticipantButton.setText("Add Participant");
        addParticipantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addParticipantButtonActionPerformed(evt);
            }
        });

        listProjectParticipantsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        listProjectParticipantsLabel.setText("List of Project Participants");

        jTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Participant Id", "Name", "Role Id", "Role"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        deleteParticipantButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        deleteParticipantButton.setForeground(new java.awt.Color(95, 10, 36));
        deleteParticipantButton.setText("Delete Participant");
        deleteParticipantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteParticipantButtonActionPerformed(evt);
            }
        });

        addParticipantButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addParticipantButton1.setForeground(new java.awt.Color(0, 95, 45));
        addParticipantButton1.setText("Next");
        addParticipantButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addParticipantButton1ActionPerformed(evt);
            }
        });

        addNewParticipantButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addNewParticipantButton.setForeground(new java.awt.Color(0, 95, 45));
        addNewParticipantButton.setText("New Participant...");
        addNewParticipantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewParticipantButtonActionPerformed(evt);
            }
        });

        addTitleComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addTitleComboBox.setForeground(new java.awt.Color(0, 95, 45));
        addTitleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Title", "Mr.", "Mrs.", "Miss.", "Dr." }));

        addTitleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addTitleLabel.setText("Title");

        firstNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name");

        firstNameTextField.setColumns(11);
        firstNameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        firstNameTextField.setToolTipText("Enter First Name");
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name");

        lastNameTextField.setColumns(11);
        lastNameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lastNameTextField.setToolTipText("Enter Last Name");

        designationLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        designationLabel.setText("Designation");

        designationTextField.setColumns(11);
        designationTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        designationTextField.setToolTipText("Enter Designation");

        addNewParticipantPanelButton.setText("Add");
        addNewParticipantPanelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewParticipantPanelButtonActionPerformed(evt);
            }
        });

        addNewParticipantRoleComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addNewParticipantRoleComboBox.setForeground(new java.awt.Color(0, 95, 45));
        addNewParticipantRoleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Role" }));
        for(int i = 0; i < participantDesignationsList.size(); i++){
            //System.out.println(participantDesignationsList.get(i).getName());
            addNewParticipantRoleComboBox.addItem(new ComboItem(participantDesignationsList.get(i).getName(), Integer.toString(participantDesignationsList.get(i).getId())));
        }
        addNewParticipantRoleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewParticipantRoleComboBoxActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        emailLabel.setText("Email");

        emailTextField.setColumns(11);
        emailTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        emailTextField.setToolTipText("Enter Last Name");

        phoneLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        phoneLabel.setText("Phone");

        phoneTextField.setColumns(11);
        phoneTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        phoneTextField.setToolTipText("Enter Last Name");

        organizationLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        organizationLabel.setText("Organization");

        organizationTextField.setColumns(11);
        organizationTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        organizationTextField.setToolTipText("Enter Designation");

        addTitleLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addTitleLabel1.setText("Role");

        javax.swing.GroupLayout addParticipantPanelLayout = new javax.swing.GroupLayout(addParticipantPanel);
        addParticipantPanel.setLayout(addParticipantPanelLayout);
        addParticipantPanelLayout.setHorizontalGroup(
            addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addParticipantPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(organizationLabel)
                    .addComponent(addTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(designationTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addTitleComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(organizationTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewParticipantRoleComboBox, 0, 180, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addParticipantPanelLayout.createSequentialGroup()
                        .addComponent(phoneLabel)
                        .addGap(40, 40, 40)
                        .addComponent(phoneTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addParticipantPanelLayout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addParticipantPanelLayout.createSequentialGroup()
                        .addComponent(lastNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lastNameTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addParticipantPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(firstNameTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addParticipantPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addNewParticipantPanelButton)))
                .addGap(28, 28, 28))
            .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addParticipantPanelLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(designationLabel)
                    .addContainerGap(523, Short.MAX_VALUE)))
        );
        addParticipantPanelLayout.setVerticalGroup(
            addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addParticipantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTitleLabel)
                    .addComponent(addTitleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(designationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLabel)
                    .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(organizationLabel)
                        .addComponent(organizationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneLabel)
                    .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addNewParticipantRoleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addTitleLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNewParticipantPanelButton)
                .addGap(79, 79, 79))
            .addGroup(addParticipantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addParticipantPanelLayout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(designationLabel)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout mainPanel3Layout = new javax.swing.GroupLayout(mainPanel3);
        mainPanel3.setLayout(mainPanel3Layout);
        mainPanel3Layout.setHorizontalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addNewProjectTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generalProjectInfoLabel3)
                    .addGroup(mainPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(mainPanel3Layout.createSequentialGroup()
                                .addComponent(deleteParticipantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addParticipantButton1))
                            .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addParticipantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(listProjectParticipantsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mainPanel3Layout.createSequentialGroup()
                                    .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPanel3Layout.createSequentialGroup()
                                            .addComponent(participantRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(participantNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(chooseParticipantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(addNewParticipantButton)
                                        .addComponent(addParticipantButton)))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        mainPanel3Layout.setVerticalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(addNewProjectTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(generalProjectInfoLabel3)
                .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(participantNameLabel))
                        .addGap(13, 13, 13)
                        .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(participantRoleLabel)
                            .addComponent(chooseParticipantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addParticipantButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addNewParticipantButton)
                .addGap(18, 18, 18)
                .addComponent(addParticipantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listProjectParticipantsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteParticipantButton)
                    .addComponent(addParticipantButton1))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        participantsScrollPane.setViewportView(mainPanel3);

        createProjectPane.addTab("Participants", participantsScrollPane);

        multimediaScrollPane.setBorder(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        addAdobeTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        addProjectButton3.setForeground(new java.awt.Color(0, 95, 45));
        addProjectButton3.setText("Next");
        addProjectButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectButton3ActionPerformed(evt);
            }
        });

        adobeFilesLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adobeFilesLabel1.setText("Select File");

        addNewProjectTextArea2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addNewProjectTextArea2.setText("Add New Project");

        addadobefileButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addadobefileButton.setForeground(new java.awt.Color(0, 95, 45));
        addadobefileButton.setText("Choose a file");
        addadobefileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addadobefileButtonActionPerformed(evt);
            }
        });

        fileNameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        fileNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameTextFieldActionPerformed(evt);
            }
        });

        cadDocumentLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cadDocumentLabel1.setText("File Type");

        generalProjectInfoLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        generalProjectInfoLabel4.setText("Step 3 - Project Multimedia");

        logoLabel4.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel4.setForeground(new java.awt.Color(0, 95, 45));
        logoLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scu-mission.png"))); // NOI18N

        fileNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        fileNameLabel.setText("File Name");

        jComboBox1.addItem("Select File Type");
        for (int i = 0; i < fileTypeList.size(); i++) {
            jComboBox1.addItem(new ComboItem(fileTypeList.get(i).getType(), Integer.toString(fileTypeList.get(i).getId())));
        }

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "File Name", "Location", "Type"
            }
        ));
        jScrollPane5.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generalProjectInfoLabel4)
                    .addComponent(addNewProjectTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(adobeFilesLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cadDocumentLabel1)
                                    .addComponent(fileNameLabel))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addAdobeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(addadobefileButton))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(fileNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(logoLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addProjectButton3)
                                        .addGap(36, 36, 36))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewProjectTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(generalProjectInfoLabel4)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addAdobeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addadobefileButton)
                            .addComponent(adobeFilesLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cadDocumentLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fileNameLabel)
                            .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addProjectButton3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(logoLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        multimediaScrollPane.setViewportView(jPanel3);

        createProjectPane.addTab("Multimedia", multimediaScrollPane);

        jScrollPane4.setBorder(null);
        jScrollPane4.setPreferredSize(new java.awt.Dimension(716, 822));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        addProjectButton.setForeground(new java.awt.Color(0, 95, 45));
        addProjectButton.setText("Create Project");
        addProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectButtonActionPerformed(evt);
            }
        });

        addNewProjectTextArea4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addNewProjectTextArea4.setText("Add New Project");

        logoLabel5.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel5.setForeground(new java.awt.Color(0, 95, 45));
        logoLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scu-mission.png"))); // NOI18N

        generalProjectInfoLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        generalProjectInfoLabel5.setText("Step 4 - Create New Project");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addNewProjectTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(logoLabel5)
                        .addGap(54, 54, 54)
                        .addComponent(addProjectButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(generalProjectInfoLabel5)))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewProjectTextArea4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(addProjectButton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(generalProjectInfoLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(logoLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(530, Short.MAX_VALUE))
        );

        jScrollPane4.setViewportView(jPanel4);

        createProjectPane.addTab("Create Project", jScrollPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createProjectPane, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createProjectPane, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void moveToParticipantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveToParticipantsActionPerformed
        createProjectPane.setSelectedIndex(1);
    }//GEN-LAST:event_moveToParticipantsActionPerformed
    private void projectIdTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        createProjectPane.setSelectedIndex(1);
    }
    private void projectStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectStatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectStatusComboBoxActionPerformed

    private void projectLocationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectLocationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectLocationTextFieldActionPerformed

    private void mechanicalEngineeringCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mechanicalEngineeringCheckBoxActionPerformed
        categorySelected.add("Mechanical Engineering");

    }//GEN-LAST:event_mechanicalEngineeringCheckBoxActionPerformed

    private void projectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectNameTextFieldActionPerformed

    private void chooseParticipantComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseParticipantComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseParticipantComboBoxActionPerformed

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void electricalEngineeringCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electricalEngineeringCheckBoxActionPerformed
        categorySelected.add("Electrical Engineering");
    }//GEN-LAST:event_electricalEngineeringCheckBoxActionPerformed

    private void bioengineeringCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioengineeringCheckBoxActionPerformed
        categorySelected.add("Bio Engineering");
    }//GEN-LAST:event_bioengineeringCheckBoxActionPerformed

    private void civilEngineeringCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilEngineeringCheckBoxActionPerformed
        categorySelected.add("Civil Engineering");
    }//GEN-LAST:event_civilEngineeringCheckBoxActionPerformed

    private void computerEngineeringCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computerEngineeringCheckBoxActionPerformed
        categorySelected.add("Computer Engineering");
    }//GEN-LAST:event_computerEngineeringCheckBoxActionPerformed

    private void scopeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scopeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scopeTextFieldActionPerformed

    private void addParticipantButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addParticipantButton1ActionPerformed
        // TODO add your handling code here:
        /*
         for (int i = 0; i < participantsList.size(); i++) {
         System.out.println("Final part id : " + participantsList.get(i).getParticipantId());
         System.out.println("Final role id : " + participantsList.get(i).getRoleId());
         }
         */
        createProjectPane.setSelectedIndex(2);
    }//GEN-LAST:event_addParticipantButton1ActionPerformed

    private void addParticipantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addParticipantButtonActionPerformed
        // TODO add your handling code here:

        if (roleComboBox.getSelectedItem().equals("Choose a Role")
                || chooseParticipantComboBox.getSelectedItem().equals("Choose a Participant")) {
            JOptionPane.showMessageDialog(mainPanel, "Please select a Participant and its Role");
        } else {
            Object roleItem = roleComboBox.getSelectedItem();
            Object participantItem = chooseParticipantComboBox.getSelectedItem();
            String roleValue = ((ComboItem) roleItem).getValue();
            String participantValue = ((ComboItem) participantItem).getValue();
            AssignParticipantsToProject a = new AssignParticipantsToProject(participantValue, roleValue);
            participantsList.add(a);
            Object[] row = {participantValue, participantItem, roleValue, roleItem};
            model = (DefaultTableModel) jTable1.getModel();
            model.addRow(row);
            /*
             System.out.println("role : " + participantsList.get(0).getRoleId());
             System.out.println("participant : " + participantsList.get(0).getParticipantId());
             */
        }



    }//GEN-LAST:event_addParticipantButtonActionPerformed

    private void deleteParticipantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteParticipantButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();

        // model.getv
        String participantId = model.getValueAt(row, 0).toString();
        String roleId = model.getValueAt(row, 2).toString();

        //System.out.println("delete participant : " + participantId);
        //System.out.println("delete role : " + roleId);
        AssignParticipantsToProject a = new AssignParticipantsToProject(participantId, roleId);
        //System.out.println("contains : " + participantsList.contains(a));
        Iterator<AssignParticipantsToProject> itr = participantsList.iterator();
        while (itr.hasNext()) {
            AssignParticipantsToProject x = itr.next();
            //System.out.println("x value : " + x.getParticipantId());
            if (a.getParticipantId() == x.getParticipantId() && a.getRoleId() == x.getRoleId()) {
                //System.out.println("Reomoved : ");
                itr.remove();
            }
        }
        model.removeRow(row);
    }//GEN-LAST:event_deleteParticipantButtonActionPerformed

    private void addCodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCodeTextFieldActionPerformed
    private void addCodeTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void addAdobeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }
    private void addLinkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLinkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addLinkTextFieldActionPerformed

    private void addLinkTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLinkTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addLinkTextField1ActionPerformed

    private void addNewParticipantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewParticipantButtonActionPerformed
        // TODO add your handling code here:
        addParticipantPanel.setVisible(true);
    }//GEN-LAST:event_addNewParticipantButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void addNewParticipantPanelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewParticipantPanelButtonActionPerformed
        // TODO add your handling code here:
        String[] array = new String[8];
        array[0] = addTitleComboBox.getSelectedItem().toString();
        array[1] = firstNameTextField.getText();
        array[2] = "";
        array[3] = lastNameTextField.getText();
        array[4] = designationTextField.getText();
        array[5] = emailTextField.getText();
        array[6] = phoneTextField.getText();
        array[7] = organizationTextField.getText();

        if (addNewParticipantRoleComboBox.getSelectedItem() == null
                || addNewParticipantRoleComboBox.getSelectedItem().equals("Choose a Role")) {
            JOptionPane.showMessageDialog(mainPanel, "Please choose a role");
        }
        else if (array[0] == null || array[0].equals("Choose a Title")) {
            JOptionPane.showMessageDialog(mainPanel, "Please choose a title");
        }
        else if (array[1] == null || array[1].equals("") || array[3] == null || array[3].equals("")) {
            JOptionPane.showMessageDialog(mainPanel, "Please enter first and last name");
        } 
        else if (!array[5].isEmpty() && !(new EmailFormatValidator()).validate(array[5])) {
            JOptionPane.showMessageDialog(mainPanel, "Please enter a valid email address");
        }
        else if (!array[6].isEmpty() && !PhoneNumberValidator.validatePhoneNumber(array[6])) {
            JOptionPane.showMessageDialog(mainPanel, "Please enter a valid phone number");
        }        
        else {
            //System.out.println("addNewParticipantRoleComboBox.getSelectedItem() = " + addNewParticipantRoleComboBox.getSelectedItem());
            boolean success = addNewProjectController.addParticipant(array);
            if (success) {
                participants = addNewProjectController.getParticipantsFromDatabase();
                this.sortParticipants();       
                chooseParticipantComboBox.removeAllItems();
                chooseParticipantComboBox.addItem("Choose A Participant");                
                for (int i = 0; i < participants.size(); i++) {
                    String fullName = participants.get(i).getNameTitle().concat(" "
                            + participants.get(i).getFirstname()).concat(" " + participants.get(i).getLastname());
                    chooseParticipantComboBox.addItem(new ComboItem(fullName, Integer.toString(participants.get(i).getId())));
                }
                //initComponents();
                Object roleItem = addNewParticipantRoleComboBox.getSelectedItem();
                String roleValue = ((ComboItem) roleItem).getValue();

                String participantValue = array[0].concat(" ").concat(array[1]).concat(" ").concat(array[3]);
                //Object participantItem = (Object)new ComboItem(participantValue, Integer.toString(participants.get(participants.size()-1).getId()));
                String participantId = Integer.toString(participants.get(participants.size() - 1).getId());
                AssignParticipantsToProject a = new AssignParticipantsToProject(participantId, roleValue);
                participantsList.add(a);
                Object[] row = {participantId, participantValue, roleValue, roleItem};
                model = (DefaultTableModel) jTable1.getModel();
                model.addRow(row);                
                JOptionPane.showMessageDialog(mainPanel, "Participant added succesfully");
            } else {
                JOptionPane.showMessageDialog(mainPanel, "Participant could not be added");
            }
        }
    }//GEN-LAST:event_addNewParticipantPanelButtonActionPerformed

    private void addNewParticipantRoleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewParticipantRoleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewParticipantRoleComboBoxActionPerformed

    private void addNewTagsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewTagsActionPerformed
        // TODO add your handling code here:
        //System.out.println("add new tags :: " +addNewTags.isSelected());
        if (addNewTags.isSelected()) {
            newTagsLabelField.setVisible(true);
            newTagsTextField.setVisible(true);
        } else if (!addNewTags.isSelected()) {
            newTagsLabelField.setVisible(false);
            newTagsTextField.setVisible(false);
        }
    }//GEN-LAST:event_addNewTagsActionPerformed

    private void addProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectButtonActionPerformed
        // TODO add your handling code here:
        final String array[] = new String[12];
        if (projectIdTextField.getText() == null || projectIdTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(mainPanel, "Please enter Distinct ID for Project");
        } else if (projectNameTextField.getText() == null || projectNameTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(mainPanel, "Please enter Project Name");
        } else if (shortDescriptionTextField.getText() == null || shortDescriptionTextField.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(mainPanel, "Please enter Short Description for Project");
        } else if (jTextArea1.getText() == null || jTextArea1.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(mainPanel, "Please enter General Description for Project");
        } else if (projectStatusComboBox.getSelectedItem().toString() == null || projectStatusComboBox.getSelectedItem().toString().trim().equals("")
                || projectStatusComboBox.getSelectedItem().toString().trim().equals("Choose a Status")) {
            JOptionPane.showMessageDialog(mainPanel, "Please select Project Status");
        } else if (categorySelected.size() < 1) {
            JOptionPane.showMessageDialog(mainPanel, "Please select Category for Project");
        } else if (null == startDate.getDate()) {
            JOptionPane.showMessageDialog(mainPanel, "Please enter Project Start Date");
        } else if (null == endDate.getDate()) {
            JOptionPane.showMessageDialog(mainPanel, "Please enter Project End Date");
        } else {

            array[0] = projectNameTextField.getText();
            array[1] = shortDescriptionTextField.getText();
            array[2] = jTextArea1.getText();
            array[3] = projectStatusComboBox.getSelectedItem().toString();
            //System.out.println("status : " + array[3]);
            array[4] = projectLocationTextField.getText();
            array[5] = startDate.getDate().toString();
            array[6] = endDate.getDate().toString();
            array[7] = scopeTextField.getText();
            array[8] = outcomeTextField.getText();
            array[9] = projectIdTextField.getText();
            selectedTagsList = projectTagsOptions.getSelectedValuesList();

            String newTags = newTagsTextField.getText();
            if (addNewTags.isSelected() && newTags != null && !newTags.equals("")) {
                String[] newTagsArr = newTags.split(";");
                addNewProjectController.addNewTags(tagsList, newTagsArr);
                for (int i = 0; i < newTagsArr.length; i++) {
                    selectedTagsList.add(newTagsArr[i]);
                }
            }

            if (civilEngineeringCheckBox.isSelected()) {
                categoriesList.add("Civil Engineering");
            }
            if (bioengineeringCheckBox.isSelected()) {
                categoriesList.add("Bio Engineering");
            }
            if (mechanicalEngineeringCheckBox.isSelected()) {
                categoriesList.add("Mechanical Engineering");
            }
            if (electricalEngineeringCheckBox.isSelected()) {
                categoriesList.add("Electrical Engineering");
            }
            if (computerEngineeringCheckBox.isSelected()) {
                categoriesList.add("Computer Engineering");
            }

            /*
            boolean success = addNewProjectController.addProject(array, categoriesList, participantsList,
                    videoList, plainTextList, adobeFileList, cadFileList, codeFileList, hyperLinkList,
                    pdfList, photosList, spreadSheetList, wordList, selectedTagsList);
            */
            
            boolean success = addNewProjectController.addProject(array, categoriesList, participantsList,
                    filesList, selectedTagsList);
            
            if (success) {
                /*for (Component C : this.getComponents()) {
                 System.out.println("ok here now :"+C.getClass());
                 if (C instanceof JTabbedPane || C instanceof JTextField || C instanceof JTextArea || C instanceof JTable) {
                 System.out.println("not here at all");
                 ((JTextComponent) C).setText(""); //abstract superclass
                 }
                 }*/

                JOptionPane.showMessageDialog(mainPanel, "New Project has been added succesfully");
            } else {
                JOptionPane.showMessageDialog(mainPanel, "New Project could not be added");
            }
        }
    }//GEN-LAST:event_addProjectButtonActionPerformed

    private void addProjectButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectButton3ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < filesList.size(); i++) {
            System.out.println("file added : " +filesList.get(i).getFilename());
            Filetypes f = filesList.get(i).getFiletypeid();
            System.out.println("file type : " +f.getId());
        }
        createProjectPane.setSelectedIndex(3);
    }//GEN-LAST:event_addProjectButton3ActionPerformed

    private void addadobefileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addadobefileButtonActionPerformed
        // TODO add your handling code here:
        //FileNameExtensionFilter filter = new FileNameExtensionFilter("Adobe Files", "pdf", "dmg");
        addAdobeTextField.setText("");
        JFileChooser chooser = new JFileChooser("File Dialog");
        //chooser.setFileFilter(filter);
        //File f = chooser.getSelectedFile();
        chooser.setMultiSelectionEnabled(true);
        chooser.showOpenDialog(this);
        File[] f = chooser.getSelectedFiles();
        String allfilenames = "";
        if (addAdobeTextField.getText() != null && addAdobeTextField.getText() != "") {
            allfilenames = addAdobeTextField.getText();
        }
        for (int i = 0; i < f.length; i++) {
            allfilenames = allfilenames.concat(f[i].getAbsolutePath()).concat(",");
        }
        addAdobeTextField.setText(allfilenames);
        String[] selectedFilePaths = addAdobeTextField.getText().split(",");

        for (int i = 0; i < selectedFilePaths.length; i++) {
            int lastIndex = selectedFilePaths[i].lastIndexOf("\\");
                int dotIndex = selectedFilePaths[i].lastIndexOf(".");
                String selectedFileName = selectedFilePaths[i].substring(lastIndex + 1, dotIndex);
                MediaAdobe m = new MediaAdobe();
                MediaAdobePK mpk = new MediaAdobePK();
                m.setTitle(selectedFileName);
                m.setFileType("PDF");
                mpk.setFilePath(selectedFilePaths[i]);
                m.setMediaAdobePK(mpk);
                adobeFileList.add(m);
            }
            /*
            for (int i = 0; i < adobeFileList.size(); i++) {
                System.out.println("name : " + adobeFileList.get(i).getTitle());
                System.out.println("name : " + adobeFileList.get(i).getMediaAdobePK().getFilePath());

            }
            */
    }//GEN-LAST:event_addadobefileButtonActionPerformed

    private void fileNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String location = addAdobeTextField.getText();
        Object typeItem = jComboBox1.getSelectedItem();
        String typeValue = ((ComboItem) typeItem).getValue();
        String name = fileNameTextField.getText();
        //System.out.println("type : " +typeItem+ " - " +typeValue);
        //System.out.println("location : " +location+ " - " +name);
        Object[] row = {name, location, typeItem};
        model1 = (DefaultTableModel) jTable2.getModel();
        model1.addRow(row);
        Projectfiles projectfiles = new Projectfiles();
        projectfiles.setFilename(name);
        projectfiles.setFilepath(location);

        Filetypes filetypes = new Filetypes(Integer.parseInt(typeValue));
        filetypes.setType(typeItem.toString());
        projectfiles.setFiletypeid(filetypes);
        filesList.add(projectfiles);

        addAdobeTextField.setText("");
        fileNameTextField.setText("");
        jComboBox1.setSelectedItem("Select File Type");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addAdobeTextField;
    private javax.swing.JButton addNewParticipantButton;
    private javax.swing.JButton addNewParticipantPanelButton;
    private javax.swing.JComboBox addNewParticipantRoleComboBox;
    private javax.swing.JLabel addNewProjectTextArea;
    private javax.swing.JLabel addNewProjectTextArea2;
    private javax.swing.JLabel addNewProjectTextArea3;
    private javax.swing.JLabel addNewProjectTextArea4;
    private javax.swing.JRadioButton addNewTags;
    private javax.swing.JButton addParticipantButton;
    private javax.swing.JButton addParticipantButton1;
    private javax.swing.JPanel addParticipantPanel;
    private javax.swing.JButton addProjectButton;
    private javax.swing.JButton addProjectButton3;
    private javax.swing.JComboBox addTitleComboBox;
    private javax.swing.JLabel addTitleLabel;
    private javax.swing.JLabel addTitleLabel1;
    private javax.swing.JButton addadobefileButton;
    private javax.swing.JLabel adobeFilesLabel1;
    private javax.swing.JCheckBox bioengineeringCheckBox;
    private javax.swing.JLabel cadDocumentLabel1;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JComboBox chooseParticipantComboBox;
    private javax.swing.JCheckBox civilEngineeringCheckBox;
    private javax.swing.JCheckBox computerEngineeringCheckBox;
    private javax.swing.JTabbedPane createProjectPane;
    private javax.swing.JButton deleteParticipantButton;
    private javax.swing.JLabel designationLabel;
    private javax.swing.JTextField designationTextField;
    private javax.swing.JCheckBox electricalEngineeringCheckBox;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel generalProjectInfoLabel;
    private javax.swing.JLabel generalProjectInfoLabel3;
    private javax.swing.JLabel generalProjectInfoLabel4;
    private javax.swing.JLabel generalProjectInfoLabel5;
    private javax.swing.JScrollPane generalinfoScrollPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel listProjectParticipantsLabel;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JLabel logoLabel4;
    private javax.swing.JLabel logoLabel5;
    private javax.swing.JLabel logoLabel6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainPanel3;
    private javax.swing.JCheckBox mechanicalEngineeringCheckBox;
    private javax.swing.JButton moveToParticipants;
    private javax.swing.JScrollPane multimediaScrollPane;
    private javax.swing.JLabel newTagsLabelField;
    private javax.swing.JTextField newTagsTextField;
    private javax.swing.JLabel organizationLabel;
    private javax.swing.JTextField organizationTextField;
    private javax.swing.JLabel outcomeLabel;
    private javax.swing.JTextField outcomeTextField;
    private javax.swing.JLabel participantNameLabel;
    private javax.swing.JLabel participantRoleLabel;
    private javax.swing.JScrollPane participantsScrollPane;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField projectIdTextField;
    private javax.swing.JTextField projectLocationTextField;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JComboBox projectStatusComboBox;
    private javax.swing.JList projectTagsOptions;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JLabel scopeLabel;
    private javax.swing.JTextField scopeTextField;
    private javax.swing.JLabel shortDescriptionLabel;
    private javax.swing.JTextField shortDescriptionTextField;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel statusProjectLabel;
    private javax.swing.JLabel tagsOptionsLabel;
    // End of variables declaration//GEN-END:variables
    
    public void sortParticipants() {
        if (participants != null) {
            Collections.sort(participants, new ParticipantsComparator());
        }
    }
    
    class ParticipantsComparator implements Comparator<Participants> {
        public int compare(Participants a, Participants b) {
            int retVal = -1;
            retVal = a.getLastname().compareToIgnoreCase(b.getLastname());
            if (retVal != 0) { return retVal; }
            else {
                return a.getFirstname().compareTo(b.getFirstname());
            }
        }
    }
}
