/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.src.frugalinnovationlab.view;

import com.src.frugalinnovationlab.Controller.EditProjectController;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Hinsen Chan
 */
public class EditProjectPanel extends javax.swing.JPanel {
    private WelcomeAbstract mainApplication;
    private EditProjectController editProjectController;

    //default constructor
    public EditProjectPanel(WelcomeAbstract welcome) {
        initComponents();
        //set reference to main app class
        this.mainApplication = welcome;
        //set reference to controller for this panel
        editProjectController = new EditProjectController(this);
        //set model for this table
        updateTable();
        //add this panel's controller as observer for this table
        jTable1.getSelectionModel().addListSelectionListener(editProjectController);          
    }

    //update table data from controller
    public void updateTable() {
        jTable1.setModel(editProjectController.getTableModel());        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editProjectsLabel = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        archiveProjectButton = new javax.swing.JButton();
        activateProjectButton = new javax.swing.JButton();
        logoLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 170, 153), 4));
        setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 600));

        editProjectsLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        editProjectsLabel.setText("Edit Projects");

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("Select a project");
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        archiveProjectButton.setForeground(new java.awt.Color(153, 0, 0));
        archiveProjectButton.setText("Archive Project");
        archiveProjectButton.setToolTipText("Archive Project and Hide for Editing and Viewing");
        archiveProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archiveProjectButtonActionPerformed(evt);
            }
        });

        activateProjectButton.setForeground(new java.awt.Color(0, 153, 102));
        activateProjectButton.setText("Activate Project");
        activateProjectButton.setToolTipText("Activate Project for Editing and Viewing");
        activateProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activateProjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(activateProjectButton)
                        .addGap(18, 18, 18)
                        .addComponent(archiveProjectButton)))
                .addContainerGap())
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archiveProjectButton)
                    .addComponent(activateProjectButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logoLabel2.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scu-mission.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(editProjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(logoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editProjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void activateProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activateProjectButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row > -1) {
            String projectName = jTable1.getModel().getValueAt(row, 0).toString();
            boolean success = editProjectController.activateProject(projectName);
            if(success) {
                updateTable();
                mainApplication.getContentPanel().remove(mainApplication.getEditProjectPanel());
                mainApplication.setEditProjectPanel(new EditProjectPanel(mainApplication));
                mainApplication.getContentPanel().add(mainApplication.getEditProjectPanel()); 
                mainApplication.getContentPanel().revalidate();
                mainApplication.getContentPanel().repaint();
                JOptionPane.showMessageDialog(tablePanel, projectName+ " is Activated !!");
            } else {
                JOptionPane.showMessageDialog(tablePanel, projectName+ " is not Activated !!");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select a project first");
        }
    }//GEN-LAST:event_activateProjectButtonActionPerformed

    private void archiveProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archiveProjectButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row > -1) {
            String projectName = jTable1.getModel().getValueAt(row, 0).toString();
            boolean success = editProjectController.deleteProject(projectName);
            if(success) {
                updateTable();
                mainApplication.getContentPanel().remove(mainApplication.getEditProjectPanel());
                mainApplication.setEditProjectPanel(new EditProjectPanel(mainApplication));
                mainApplication.getContentPanel().add(mainApplication.getEditProjectPanel()); 
                mainApplication.getContentPanel().revalidate();
                mainApplication.getContentPanel().repaint();
                JOptionPane.showMessageDialog(tablePanel, projectName+ " is Archived !!");
            } else {
                JOptionPane.showMessageDialog(tablePanel, projectName+ " is not Archived !!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a project first");
        }
    }//GEN-LAST:event_archiveProjectButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton activateProjectButton;
    private javax.swing.JButton archiveProjectButton;
    private javax.swing.JLabel editProjectsLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JPanel tablePanel;
    // End of variables declaration//GEN-END:variables
    //return reference to main app class
    public WelcomeAbstract getMainApplication() {
        return mainApplication;
    }
    //return table in this panel
    public JTable getJTable() {
        return jTable1;
    }
}
