/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.src.frugalinnovationlab.view;

import com.src.frugalinnovationlab.Controller.ManageAccountInfoController;
import com.src.frugalinnovationlab.Entity.Users;
import com.src.frugalinnovationlab.helper.Constants;
import java.awt.Color;
import java.awt.Graphics2D;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.Painter;
import javax.swing.UIDefaults;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author diptik
 */
public class ManageAccountInfoPanel extends javax.swing.JPanel {

    Preferences prefs = Preferences.userNodeForPackage(com.src.frugalinnovationlab.Service.LoginService.class);
    String defaultUserValue = "";
    private ManageAccountInfoController manageAccountInfoController;
    Users user;

    /**
     * Creates new form ManageAccountInfoPanel
     */
    public ManageAccountInfoPanel() {
        manageAccountInfoController = new ManageAccountInfoController(this);

        initComponents();
    }

    public ManageAccountInfoPanel(Users user1) {
        initComponents();
        manageAccountInfoController = new ManageAccountInfoController(this);
        String loggedinUserValue = prefs.get(Constants.USER_NAME, defaultUserValue);
        System.out.println("logged in username : " + loggedinUserValue);
        user = manageAccountInfoController.getLogInUserDetails(loggedinUserValue);
        System.out.println("user first name : " +user.getFirstname());
        firstNameTextField.setText(user.getFirstname());       
        lastNameTextField.setText(user.getLastname());
        emailTextField.setText(user.getEmailaddress());
        phoneNumberTextField.setText(String.valueOf(user.getContactnumber()));
        userNameTextField.setText(user.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        addNewUserTextArea = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        userNameTextField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        reenterPasswordField = new javax.swing.JPasswordField();
        reenterPasswordLabel = new javax.swing.JLabel();
        enterPasswordField = new javax.swing.JPasswordField();
        logoLabel2 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 170, 153), 4));

        centerPanel.setBackground(new java.awt.Color(255, 255, 255));
        centerPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        centerPanel.setInheritsPopupMenu(true);
        centerPanel.setPreferredSize(new java.awt.Dimension(400, 400));
        centerPanel.setRequestFocusEnabled(false);

        addNewUserTextArea.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addNewUserTextArea.setText("Update User Info");

        firstNameTextField.setColumns(11);
        firstNameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        firstNameTextField.setToolTipText("");
        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameTextField.setColumns(11);
        lastNameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        emailTextField.setColumns(11);
        emailTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        phoneNumberTextField.setColumns(11);
        phoneNumberTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        userNameTextField.setColumns(11);
        userNameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        userNameTextField.setEnabled(false);

        firstNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        firstNameLabel.setText("First Name");

        lastNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name");

        emailLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        emailLabel.setText("Email Address");

        phoneNumberLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        phoneNumberLabel.setText("Phone Number");

        userNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        userNameLabel.setText("UserName");

        passwordLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        passwordLabel.setText("Password");

        updateButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(0, 95, 45));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        reenterPasswordField.setColumns(11);
        reenterPasswordField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        reenterPasswordLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        reenterPasswordLabel.setText("Re-enter Password");

        enterPasswordField.setColumns(11);
        enterPasswordField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        enterPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                enterPasswordFieldKeyTyped(evt);
            }
        });

        logoLabel2.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scu-mission.png"))); // NOI18N

        jLabel1.setText("Password Strength");

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addComponent(addNewUserTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(centerPanelLayout.createSequentialGroup()
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel)
                            .addComponent(phoneNumberLabel)
                            .addComponent(userNameLabel)
                            .addComponent(passwordLabel)
                            .addComponent(reenterPasswordLabel))
                        .addGap(18, 18, 18)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(updateButton)
                                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailTextField)
                                    .addComponent(phoneNumberTextField)
                                    .addComponent(userNameTextField)
                                    .addComponent(reenterPasswordField)
                                    .addComponent(enterPasswordField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap())))
            .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(centerPanelLayout.createSequentialGroup()
                    .addGap(212, 212, 212)
                    .addComponent(logoLabel2)
                    .addContainerGap(212, Short.MAX_VALUE)))
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addNewUserTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordLabel)
                        .addComponent(enterPasswordField))
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reenterPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reenterPasswordLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateButton)
                .addContainerGap(297, Short.MAX_VALUE))
            .addGroup(centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(centerPanelLayout.createSequentialGroup()
                    .addGap(119, 119, 119)
                    .addComponent(logoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        
        String []array = new String[7];
        array[0] = firstNameTextField.getText();
        array[1] = lastNameTextField.getText();
        array[2] = emailTextField.getText();
        array[3] = phoneNumberTextField.getText();
        array[4] = userNameTextField.getText();
        array[5] = String.valueOf(enterPasswordField.getPassword());
        array[6] = String.valueOf(reenterPasswordField.getPassword());
        
        if(array[0].equals("") || array[1].equals("") || array[2].equals("") || array[3].equals("") || array[5].equals("") || array[6].equals("")){
            JOptionPane.showMessageDialog(centerPanel, "Please enter complete Details with Password Confirmation");
        } else if (!array[5].equals(array[6])){
            JOptionPane.showMessageDialog(centerPanel, "Passwords do not match");
        } else {
            boolean success = manageAccountInfoController.updateUserDetails(array);
            if(success){
                JOptionPane.showMessageDialog(centerPanel, "Details Updated Successfully");          
            } else {
                JOptionPane.showMessageDialog(centerPanel, "Details updation didn't complete");
            }
        }
         
    }//GEN-LAST:event_updateButtonActionPerformed

    private void enterPasswordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enterPasswordFieldKeyTyped
        // TODO add your handling code here:
        enterPasswordField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void changedUpdate(DocumentEvent e) {
                updateLabel(e);
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateLabel(e);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateLabel(e);
            }

            private void updateLabel(DocumentEvent e) {
                String text = String.valueOf(enterPasswordField.getPassword());

                if (text.length() < 7) {
                    progressBar.setValue(0);
                } else if (text.matches("[a-z]+")) {
                    progressBar.setValue(15);
                    UIDefaults defaults = new UIDefaults();
                    defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.RED));
                    defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.RED));
                    progressBar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
                    progressBar.putClientProperty("Nimbus.Overrides", defaults);
                } else if (text.matches("[a-zA-Z]+") || text.matches("[A-Za-z]+")) {
                    progressBar.setValue(30);
                    UIDefaults defaults = new UIDefaults();
                    defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.ORANGE));
                    defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.ORANGE));
                    progressBar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
                    progressBar.putClientProperty("Nimbus.Overrides", defaults);
                } else if (text.matches("[a-zA-Z0-9]+") || text.matches("[0-9a-zA-Z]+") || text.matches("[a-z0-9A-Z]+")) {
                    progressBar.setValue(60);
                    UIDefaults defaults = new UIDefaults();
                    defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.MAGENTA));
                    defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.MAGENTA));
                    progressBar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
                    progressBar.putClientProperty("Nimbus.Overrides", defaults);
                } else if (text.matches(".*[\\d\\W]")) {
                    progressBar.setValue(100);
                    UIDefaults defaults = new UIDefaults();
                    defaults.put("ProgressBar[Enabled].foregroundPainter", new MyPainter(Color.GREEN));
                    defaults.put("ProgressBar[Enabled+Finished].foregroundPainter", new MyPainter(Color.GREEN));
                    progressBar.putClientProperty("Nimbus.Overrides.InheritDefaults", Boolean.TRUE);
                    progressBar.putClientProperty("Nimbus.Overrides", defaults);
                }
            }
        });
    }//GEN-LAST:event_enterPasswordFieldKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addNewUserTextArea;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPasswordField enterPasswordField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JPasswordField reenterPasswordField;
    private javax.swing.JLabel reenterPasswordLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}

class MyPainter implements Painter<JProgressBar> {

    private final Color color;

    public MyPainter(Color c1) {
        this.color = c1;
    }

    @Override
    public void paint(Graphics2D gd, JProgressBar t, int width, int height) {
        gd.setColor(color);
        gd.fillRect(0, 0, width, height);
    }
}