/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.src.frugalinnovationlab.view;

import com.src.frugalinnovationlab.Controller.ViewProjectController;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author diptik
 */
public class ViewProjectPanel extends javax.swing.JPanel {
    private Welcome mainApplication;
    private JTable jtable1;
    private ViewProjectController viewProjectController;

    /**
     * Creates new form ViewAllProjectsPanel
     */
    public ViewProjectPanel(Welcome welcome) {
        initComponents();
        this.mainApplication = welcome;
        viewProjectController = new ViewProjectController(this);
        addJTable();
        jtable1.getSelectionModel().addListSelectionListener(viewProjectController);                
    }

    public void addJTable() {
        // add the data and column names to a JTable  

        jtable1 = new JTable(viewProjectController.getTableModel());


        final JScrollPane scrollpane = new JScrollPane(jtable1, JScrollPane.VERTICAL_SCROLLBAR_NEVER, JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        tablePanel.setLayout(new BorderLayout());
        tablePanel.add(scrollpane, BorderLayout.CENTER);

        final int rows = 14;

        Dimension d = jtable1.getPreferredSize();
        scrollpane.setPreferredSize(new Dimension(d.width, jtable1.getRowHeight() * rows));

        JPanel navigation = new JPanel(new FlowLayout(FlowLayout.CENTER));


        JButton next = new JButton(">");
        next.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                int height = jtable1.getRowHeight() * (rows - 2);

                JScrollBar bar = scrollpane.getVerticalScrollBar();
                bar.setValue(bar.getValue() + height);
            }
        });
        JButton previous = new JButton("<");
        previous.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae) {
                int height = jtable1.getRowHeight() * (rows - 2);

                JScrollBar bar = scrollpane.getVerticalScrollBar();
                bar.setValue(bar.getValue() - height);
            }
        });

        navigation.add(previous);
        navigation.add(next);


        tablePanel.add(navigation, BorderLayout.SOUTH);



    }

    public void updateTable() {

        jtable1.setModel(viewProjectController.getTableModel());




    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewAllProjectsLabel = new javax.swing.JLabel();
        tablePanel = new javax.swing.JPanel();
        logoLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(150, 170, 153), 4));
        setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 600));

        viewAllProjectsLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        viewAllProjectsLabel.setText("View All Projects");

        tablePanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        logoLabel2.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scu-mission.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(viewAllProjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(logoLabel2)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewAllProjectsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(tablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel viewAllProjectsLabel;
    // End of variables declaration//GEN-END:variables
    public Welcome getMainApplication() {
        return mainApplication;
    }
}
