/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.src.frugalinnovationlab.view;

/**
 *
 * @author diptik
 */
public class ViewSpecificProjectPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewProjectPanel
     */
    public ViewSpecificProjectPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        editProjectTextArea = new javax.swing.JPanel();
        addNewUserTextArea = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        shortDescriptionTextField = new javax.swing.JTextField();
        projectNameLabel = new javax.swing.JLabel();
        shortDescriptionLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        generalProjectInfoLabel = new javax.swing.JLabel();
        statusProjectLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        bioengineeringCheckBox = new javax.swing.JCheckBox();
        computerEngineeringCheckBox = new javax.swing.JCheckBox();
        aerospaceEngineeringCheckBox = new javax.swing.JCheckBox();
        civilEngineeringCheckBox = new javax.swing.JCheckBox();
        mechanicalEngineeringCheckBox = new javax.swing.JCheckBox();
        structuralEngineeringCheckBox = new javax.swing.JCheckBox();
        otherCheckBox = new javax.swing.JCheckBox();
        electricalEngineeringCheckBox = new javax.swing.JCheckBox();
        locationLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        projectStatusComboBox = new javax.swing.JComboBox();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        endDateTextField = new javax.swing.JTextField();
        addProjectButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        mainPanel3 = new javax.swing.JPanel();
        addNewUserTextArea3 = new javax.swing.JLabel();
        participantRoleLabel = new javax.swing.JLabel();
        generalProjectInfoLabel3 = new javax.swing.JLabel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        roleComboBox = new javax.swing.JComboBox();
        participantNameLabel = new javax.swing.JLabel();
        chooseParticipantComboBox = new javax.swing.JComboBox();
        addParticipantButton = new javax.swing.JButton();
        listProjectParticipantsLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteParticipantButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        mainPanel2 = new javax.swing.JPanel();
        addNewUserTextArea1 = new javax.swing.JLabel();
        plainTextFileLabel = new javax.swing.JLabel();
        wordDocumentLabel = new javax.swing.JLabel();
        photosLabel = new javax.swing.JLabel();
        generalProjectInfoLabel2 = new javax.swing.JLabel();
        codeLabel = new javax.swing.JLabel();
        locationClientMapLabel = new javax.swing.JLabel();
        videoLabel = new javax.swing.JLabel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        hyperlinkLabel = new javax.swing.JLabel();
        pdfLabel = new javax.swing.JLabel();
        cadDocumentLabel = new javax.swing.JLabel();
        spreadsheetLabel = new javax.swing.JLabel();
        adobeFilesLabel = new javax.swing.JLabel();
        addadobefileButton = new javax.swing.JButton();
        addCADDocumentButton = new javax.swing.JButton();
        addCodeButton = new javax.swing.JButton();
        addHyperlinkButton = new javax.swing.JButton();
        addLocationClientMapButton = new javax.swing.JButton();
        addPDFButton = new javax.swing.JButton();
        addPhotoButton = new javax.swing.JButton();
        addPlainTextFileButton = new javax.swing.JButton();
        addSpreadsheetButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        addWordDocumentButton = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 95, 45));
        jTabbedPane1.setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        editProjectTextArea.setBackground(new java.awt.Color(255, 255, 255));
        editProjectTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        editProjectTextArea.setInheritsPopupMenu(true);
        editProjectTextArea.setPreferredSize(new java.awt.Dimension(400, 400));
        editProjectTextArea.setRequestFocusEnabled(false);

        addNewUserTextArea.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addNewUserTextArea.setText("Edit Project");

        projectNameTextField.setColumns(20);
        projectNameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        projectNameTextField.setText("Enter Project Name");
        projectNameTextField.setToolTipText("");
        projectNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectNameTextFieldActionPerformed(evt);
            }
        });

        shortDescriptionTextField.setColumns(20);
        shortDescriptionTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        shortDescriptionTextField.setText("Enter Short Description");

        projectNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        projectNameLabel.setText("Project Name");
        projectNameLabel.setToolTipText("");

        shortDescriptionLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        shortDescriptionLabel.setText("Short Description");
        shortDescriptionLabel.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("General Description");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Enter Long Description");
        jScrollPane1.setViewportView(jTextArea1);

        generalProjectInfoLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        generalProjectInfoLabel.setText("General Project Information");

        statusProjectLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        statusProjectLabel.setText("Status of Project");

        categoryLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        categoryLabel.setText("Category");

        bioengineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        bioengineeringCheckBox.setText("Bioengineering");

        computerEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        computerEngineeringCheckBox.setText("Computer Engineering");

        aerospaceEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        aerospaceEngineeringCheckBox.setText("Aerospace Engineering");

        civilEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        civilEngineeringCheckBox.setText("Civil Engineering");

        mechanicalEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        mechanicalEngineeringCheckBox.setText("Mechanical Engineering");
        mechanicalEngineeringCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mechanicalEngineeringCheckBoxActionPerformed(evt);
            }
        });

        structuralEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        structuralEngineeringCheckBox.setText("Structural Engineering");

        otherCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        otherCheckBox.setText("Other");
        otherCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherCheckBoxActionPerformed(evt);
            }
        });

        electricalEngineeringCheckBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        electricalEngineeringCheckBox.setText("Electrical Engineering");

        locationLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        locationLabel.setText("Location");

        jTextField1.setColumns(20);
        jTextField1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTextField1.setText("Enter Location of Project");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));

        projectStatusComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        projectStatusComboBox.setForeground(new java.awt.Color(0, 95, 45));
        projectStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aborted", "Active", "Completed", "Dormant" }));
        projectStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectStatusComboBoxActionPerformed(evt);
            }
        });

        startDateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        startDateLabel.setText("Start Date");

        endDateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        endDateLabel.setText("End Date");

        startDateTextField.setText("MM/DD/YY");

        endDateTextField.setText("MM/DD/YY");

        addProjectButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addProjectButton.setText("Add Project");
        addProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editProjectTextAreaLayout = new javax.swing.GroupLayout(editProjectTextArea);
        editProjectTextArea.setLayout(editProjectTextAreaLayout);
        editProjectTextAreaLayout.setHorizontalGroup(
            editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                                .addComponent(shortDescriptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addComponent(projectNameLabel)
                            .addComponent(statusProjectLabel)
                            .addComponent(categoryLabel)
                            .addComponent(locationLabel)
                            .addComponent(startDateLabel)
                            .addComponent(endDateLabel))
                        .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(shortDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                                        .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(aerospaceEngineeringCheckBox)
                                            .addComponent(bioengineeringCheckBox)
                                            .addComponent(civilEngineeringCheckBox)
                                            .addComponent(computerEngineeringCheckBox))
                                        .addGap(0, 0, 0)
                                        .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mechanicalEngineeringCheckBox)
                                            .addComponent(electricalEngineeringCheckBox)
                                            .addComponent(structuralEngineeringCheckBox)
                                            .addComponent(otherCheckBox)))
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(addNewUserTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generalProjectInfoLabel))
                .addGap(139, 139, 139))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editProjectTextAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addProjectButton)
                .addGap(175, 175, 175))
        );
        editProjectTextAreaLayout.setVerticalGroup(
            editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(addNewUserTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(generalProjectInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectNameLabel)
                    .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shortDescriptionLabel)
                    .addComponent(shortDescriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2))
                    .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(statusProjectLabel))
                    .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(projectStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryLabel)
                    .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aerospaceEngineeringCheckBox)
                        .addComponent(electricalEngineeringCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                        .addComponent(bioengineeringCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(civilEngineeringCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(computerEngineeringCheckBox)
                            .addComponent(otherCheckBox)))
                    .addGroup(editProjectTextAreaLayout.createSequentialGroup()
                        .addComponent(mechanicalEngineeringCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(structuralEngineeringCheckBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDateLabel)
                    .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editProjectTextAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDateLabel)
                    .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProjectButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editProjectTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editProjectTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("General Details", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel3.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel3.setInheritsPopupMenu(true);
        mainPanel3.setPreferredSize(new java.awt.Dimension(400, 400));
        mainPanel3.setRequestFocusEnabled(false);

        addNewUserTextArea3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addNewUserTextArea3.setText("Edit Project");

        participantRoleLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        participantRoleLabel.setText("Participant Name");

        generalProjectInfoLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        generalProjectInfoLabel3.setText("Project Participants");

        roleComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Role", "Advisor", "Partner", "Student" }));
        roleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBoxActionPerformed(evt);
            }
        });

        participantNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        participantNameLabel.setText("Participant Role");

        chooseParticipantComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        chooseParticipantComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose A Participant", " " }));
        chooseParticipantComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseParticipantComboBoxActionPerformed(evt);
            }
        });

        addParticipantButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addParticipantButton.setText("Add Participant");

        listProjectParticipantsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        listProjectParticipantsLabel.setText("List of Project Participants");

        jTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Role"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        deleteParticipantButton.setText("Delete Participant from Project");

        javax.swing.GroupLayout mainPanel3Layout = new javax.swing.GroupLayout(mainPanel3);
        mainPanel3.setLayout(mainPanel3Layout);
        mainPanel3Layout.setHorizontalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel3Layout.createSequentialGroup()
                .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanel3Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(mainPanel3Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(participantRoleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chooseParticipantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(addNewUserTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(generalProjectInfoLabel3)
                                    .addGroup(mainPanel3Layout.createSequentialGroup()
                                        .addGap(205, 205, 205)
                                        .addComponent(roleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(listProjectParticipantsLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(mainPanel3Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addParticipantButton)
                    .addComponent(deleteParticipantButton, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
            .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanel3Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(participantNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(758, Short.MAX_VALUE)))
        );
        mainPanel3Layout.setVerticalGroup(
            mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(addNewUserTextArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(generalProjectInfoLabel3)
                .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(participantRoleLabel)
                            .addComponent(chooseParticipantComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addParticipantButton)
                .addGap(24, 24, 24)
                .addComponent(listProjectParticipantsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteParticipantButton)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(mainPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanel3Layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(participantNameLabel)
                    .addContainerGap(410, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Participants", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel2.setBackground(new java.awt.Color(127, 156, 144));
        mainPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mainPanel2.setInheritsPopupMenu(true);
        mainPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        mainPanel2.setRequestFocusEnabled(false);

        addNewUserTextArea1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        addNewUserTextArea1.setText("Edit Project");

        plainTextFileLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        plainTextFileLabel.setText("Plain Text Files");
        plainTextFileLabel.setToolTipText("");

        wordDocumentLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        wordDocumentLabel.setText("Word Documents");
        wordDocumentLabel.setToolTipText("");

        photosLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        photosLabel.setText("Photos");

        generalProjectInfoLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        generalProjectInfoLabel2.setText("Project Multimedia");

        codeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        codeLabel.setText("Code");

        locationClientMapLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        locationClientMapLabel.setText("Location/Client Map");

        videoLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        videoLabel.setText("Video");

        hyperlinkLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        hyperlinkLabel.setText("HyperLinks");

        pdfLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        pdfLabel.setText("PDF");

        cadDocumentLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        cadDocumentLabel.setText("CAD Documents");

        spreadsheetLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        spreadsheetLabel.setText("Spreadsheets");

        adobeFilesLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        adobeFilesLabel.setText("Adobe Files");

        addadobefileButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addadobefileButton.setText("Add Adobe File");

        addCADDocumentButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addCADDocumentButton.setText("Add Adobe File");
        addCADDocumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCADDocumentButtonActionPerformed(evt);
            }
        });

        addCodeButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addCodeButton.setText("Add Code");

        addHyperlinkButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addHyperlinkButton.setText("Add HyperLink");

        addLocationClientMapButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addLocationClientMapButton.setText("Add Location/Client Map");

        addPDFButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addPDFButton.setText("Add PDF");

        addPhotoButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addPhotoButton.setText("Add Photo");
        addPhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPhotoButtonActionPerformed(evt);
            }
        });

        addPlainTextFileButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addPlainTextFileButton.setText("Add Plain Text File");

        addSpreadsheetButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addSpreadsheetButton.setText("Add SpreadSheet");

        addButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addButton.setText("Add Video");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        addWordDocumentButton.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        addWordDocumentButton.setText("Add Word Document");
        addWordDocumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWordDocumentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanel2Layout = new javax.swing.GroupLayout(mainPanel2);
        mainPanel2.setLayout(mainPanel2Layout);
        mainPanel2Layout.setHorizontalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewUserTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generalProjectInfoLabel2)
                    .addGroup(mainPanel2Layout.createSequentialGroup()
                        .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanel2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(adobeFilesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codeLabel)
                                    .addGroup(mainPanel2Layout.createSequentialGroup()
                                        .addComponent(cadDocumentLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(hyperlinkLabel)
                                    .addComponent(locationClientMapLabel)
                                    .addComponent(pdfLabel)
                                    .addComponent(photosLabel)
                                    .addComponent(plainTextFileLabel)
                                    .addComponent(spreadsheetLabel)
                                    .addComponent(wordDocumentLabel)
                                    .addComponent(videoLabel))))
                        .addGap(28, 28, 28)
                        .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCADDocumentButton)
                            .addComponent(addadobefileButton)
                            .addComponent(addCodeButton)
                            .addComponent(addHyperlinkButton)
                            .addComponent(addLocationClientMapButton)
                            .addComponent(addPDFButton)
                            .addComponent(addPhotoButton)
                            .addComponent(addPlainTextFileButton)
                            .addComponent(addSpreadsheetButton)
                            .addComponent(addButton)
                            .addComponent(addWordDocumentButton))))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        mainPanel2Layout.setVerticalGroup(
            mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(addNewUserTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(generalProjectInfoLabel2)
                .addGap(10, 10, 10)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adobeFilesLabel)
                    .addComponent(addadobefileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadDocumentLabel)
                    .addComponent(addCADDocumentButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codeLabel)
                    .addComponent(addCodeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hyperlinkLabel)
                    .addComponent(addHyperlinkButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationClientMapLabel)
                    .addComponent(addLocationClientMapButton))
                .addGap(12, 12, 12)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pdfLabel)
                    .addComponent(addPDFButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photosLabel)
                    .addComponent(addPhotoButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plainTextFileLabel)
                    .addComponent(addPlainTextFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spreadsheetLabel)
                    .addComponent(addSpreadsheetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(videoLabel)
                    .addComponent(addButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordDocumentLabel)
                    .addComponent(addWordDocumentButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Multimedia", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mechanicalEngineeringCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mechanicalEngineeringCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mechanicalEngineeringCheckBoxActionPerformed

    private void projectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectNameTextFieldActionPerformed

    private void projectStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectStatusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectStatusComboBoxActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void otherCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherCheckBoxActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonActionPerformed

    private void addCADDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCADDocumentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCADDocumentButtonActionPerformed

    private void addPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPhotoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addPhotoButtonActionPerformed

    private void addWordDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWordDocumentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addWordDocumentButtonActionPerformed

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void chooseParticipantComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseParticipantComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseParticipantComboBoxActionPerformed

    private void addProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProjectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addCADDocumentButton;
    private javax.swing.JButton addCodeButton;
    private javax.swing.JButton addHyperlinkButton;
    private javax.swing.JButton addLocationClientMapButton;
    private javax.swing.JLabel addNewUserTextArea;
    private javax.swing.JLabel addNewUserTextArea1;
    private javax.swing.JLabel addNewUserTextArea3;
    private javax.swing.JButton addPDFButton;
    private javax.swing.JButton addParticipantButton;
    private javax.swing.JButton addPhotoButton;
    private javax.swing.JButton addPlainTextFileButton;
    private javax.swing.JButton addProjectButton;
    private javax.swing.JButton addSpreadsheetButton;
    private javax.swing.JButton addWordDocumentButton;
    private javax.swing.JButton addadobefileButton;
    private javax.swing.JLabel adobeFilesLabel;
    private javax.swing.JCheckBox aerospaceEngineeringCheckBox;
    private javax.swing.JCheckBox bioengineeringCheckBox;
    private javax.swing.JLabel cadDocumentLabel;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JComboBox chooseParticipantComboBox;
    private javax.swing.JCheckBox civilEngineeringCheckBox;
    private javax.swing.JLabel codeLabel;
    private javax.swing.JCheckBox computerEngineeringCheckBox;
    private javax.swing.JButton deleteParticipantButton;
    private javax.swing.JPanel editProjectTextArea;
    private javax.swing.JCheckBox electricalEngineeringCheckBox;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JLabel generalProjectInfoLabel;
    private javax.swing.JLabel generalProjectInfoLabel2;
    private javax.swing.JLabel generalProjectInfoLabel3;
    private javax.swing.JLabel hyperlinkLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel listProjectParticipantsLabel;
    private javax.swing.JLabel locationClientMapLabel;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JPanel mainPanel2;
    private javax.swing.JPanel mainPanel3;
    private javax.swing.JCheckBox mechanicalEngineeringCheckBox;
    private javax.swing.JCheckBox otherCheckBox;
    private javax.swing.JLabel participantNameLabel;
    private javax.swing.JLabel participantRoleLabel;
    private javax.swing.JLabel pdfLabel;
    private javax.swing.JLabel photosLabel;
    private javax.swing.JLabel plainTextFileLabel;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JComboBox projectStatusComboBox;
    private javax.swing.JComboBox roleComboBox;
    private javax.swing.JLabel shortDescriptionLabel;
    private javax.swing.JTextField shortDescriptionTextField;
    private javax.swing.JLabel spreadsheetLabel;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JLabel statusProjectLabel;
    private javax.swing.JCheckBox structuralEngineeringCheckBox;
    private javax.swing.JLabel videoLabel;
    private javax.swing.JLabel wordDocumentLabel;
    // End of variables declaration//GEN-END:variables
}
