/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.src.frugalinnovationlab.view;

import com.src.frugalinnovationlab.Controller.ViewGeneralProjectInformationController;
import com.src.frugalinnovationlab.Entity.Project;
import com.src.frugalinnovationlab.Entity.ProjectCategory;
import com.src.frugalinnovationlab.Entity.ProjectStatus;
import java.util.List;
import com.src.frugalinnovationlab.Wrappers.ComboItem;
import java.util.ArrayList;
import java.util.Set;
import javax.swing.ListSelectionModel;

/**
 *
 * @author fattymcphatfat
 */
public class ViewGeneralProjectInformation extends javax.swing.JPanel {
    ViewGeneralProjectInformationController viewGeneralProjectInformationController;
    List<Project> projectList;
    List<String> categoriesList;
    List<ProjectStatus> projectStatusList;

    /**
     * Creates new form ViewGeneralProjectInformation
     */
    public ViewGeneralProjectInformation() {
        categoriesList = new ArrayList<String>();
        viewGeneralProjectInformationController = new ViewGeneralProjectInformationController(this);
        projectStatusList = viewGeneralProjectInformationController.getProjectStatusFromDatabase();
        projectList = viewGeneralProjectInformationController.getProjectsFromDatabase();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainScrollPane = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        viewGenProjInfoLabel = new javax.swing.JLabel();
        chooseProjectComboBox = new javax.swing.JComboBox();
        bottomPanel = new javax.swing.JPanel();
        projectNameLabel = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        shortDescLabel = new javax.swing.JLabel();
        shortDescTextField = new javax.swing.JTextField();
        genDescLabel = new javax.swing.JLabel();
        genDescScrollPane = new javax.swing.JScrollPane();
        genDescTextArea = new javax.swing.JTextArea();
        statusLabel = new javax.swing.JLabel();
        statusTextField = new javax.swing.JTextField();
        categoriesLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        locationTextField = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        startDateTextField = new javax.swing.JTextField();
        outcomeLabel = new javax.swing.JLabel();
        scopeTextField = new javax.swing.JTextField();
        scopeLabel = new javax.swing.JLabel();
        outcomeScrollPane = new javax.swing.JScrollPane();
        outcomeTextArea = new javax.swing.JTextArea();
        endDateLabel = new javax.swing.JLabel();
        endDateTextField = new javax.swing.JTextField();
        categoryScrollPane = new javax.swing.JScrollPane();
        categoryTextArea = new javax.swing.JTextArea();
        logoLabel2 = new javax.swing.JLabel();

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(600, 900));
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 900));

        topPanel.setBackground(new java.awt.Color(255, 255, 255));

        viewGenProjInfoLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        viewGenProjInfoLabel.setText("View General Project Information");

        chooseProjectComboBox.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        chooseProjectComboBox.setForeground(new java.awt.Color(0, 95, 45));
        chooseProjectComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose a Project" }));
        for (int i = 0; i < projectList.size(); i++) {
            System.out.println("id : " +projectList.get(i).getId());
            chooseProjectComboBox.addItem(new ComboItem(projectList.get(i).getName(),
                String.valueOf(projectList.get(i).getId())));
    }
    chooseProjectComboBox.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            chooseProjectComboBoxActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
    topPanel.setLayout(topPanelLayout);
    topPanelLayout.setHorizontalGroup(
        topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(topPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(viewGenProjInfoLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
            .addComponent(chooseProjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    topPanelLayout.setVerticalGroup(
        topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(topPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(viewGenProjInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(chooseProjectComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    bottomPanel.setBackground(new java.awt.Color(255, 255, 255));

    projectNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    projectNameLabel.setText("Project Name");
    projectNameLabel.setToolTipText("");

    projectNameTextField.setColumns(20);
    projectNameTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    projectNameTextField.setToolTipText("Enter Project Name");
    projectNameTextField.setFocusable(false);
    projectNameTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            projectNameTextFieldActionPerformed(evt);
        }
    });

    shortDescLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    shortDescLabel.setText("Short Description");
    shortDescLabel.setToolTipText("");

    shortDescTextField.setColumns(20);
    shortDescTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    shortDescTextField.setToolTipText("Enter Project Name");
    shortDescTextField.setFocusable(false);
    shortDescTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            shortDescTextFieldActionPerformed(evt);
        }
    });

    genDescLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    genDescLabel.setText("General Description");
    genDescLabel.setToolTipText("");

    genDescTextArea.setColumns(20);
    genDescTextArea.setRows(5);
    genDescTextArea.setFocusable(false);
    genDescScrollPane.setViewportView(genDescTextArea);

    statusLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    statusLabel.setText("Status");
    statusLabel.setToolTipText("");

    statusTextField.setColumns(20);
    statusTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    statusTextField.setToolTipText("Enter Project Name");
    statusTextField.setFocusable(false);
    statusTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            statusTextFieldActionPerformed(evt);
        }
    });

    categoriesLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    categoriesLabel.setText("Categories");
    categoriesLabel.setToolTipText("");

    startDateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    startDateLabel.setText("Start Date");
    startDateLabel.setToolTipText("");

    locationTextField.setColumns(20);
    locationTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    locationTextField.setToolTipText("Enter Project Name");
    locationTextField.setFocusable(false);
    locationTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            locationTextFieldActionPerformed(evt);
        }
    });

    locationLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    locationLabel.setText("Location");
    locationLabel.setToolTipText("");

    startDateTextField.setColumns(20);
    startDateTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    startDateTextField.setToolTipText("Enter Project Name");
    startDateTextField.setFocusable(false);
    startDateTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            startDateTextFieldActionPerformed(evt);
        }
    });

    outcomeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    outcomeLabel.setText("Outcome");
    outcomeLabel.setToolTipText("");

    scopeTextField.setColumns(20);
    scopeTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    scopeTextField.setToolTipText("Enter Project Name");
    scopeTextField.setFocusable(false);
    scopeTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            scopeTextFieldActionPerformed(evt);
        }
    });

    scopeLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    scopeLabel.setText("Scope");
    scopeLabel.setToolTipText("");

    outcomeTextArea.setColumns(20);
    outcomeTextArea.setRows(5);
    outcomeTextArea.setFocusable(false);
    outcomeScrollPane.setViewportView(outcomeTextArea);

    endDateLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    endDateLabel.setText("End Date");
    endDateLabel.setToolTipText("");

    endDateTextField.setColumns(20);
    endDateTextField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
    endDateTextField.setToolTipText("Enter Project Name");
    endDateTextField.setFocusable(false);
    endDateTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            endDateTextFieldActionPerformed(evt);
        }
    });

    categoryTextArea.setColumns(15);
    categoryTextArea.setRows(1);
    categoryTextArea.setTabSize(2);
    categoryScrollPane.setViewportView(categoryTextArea);

    logoLabel2.setBackground(new java.awt.Color(255, 255, 255));
    logoLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scu-mission.png"))); // NOI18N

    javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
    bottomPanel.setLayout(bottomPanelLayout);
    bottomPanelLayout.setHorizontalGroup(
        bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bottomPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottomPanelLayout.createSequentialGroup()
                    .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(outcomeScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scopeTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(projectNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(shortDescTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(genDescScrollPane, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGap(61, 61, 61))
                .addGroup(bottomPanelLayout.createSequentialGroup()
                    .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(locationTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(shortDescLabel)
                                .addComponent(genDescLabel)
                                .addComponent(outcomeLabel)
                                .addComponent(scopeLabel)
                                .addComponent(locationLabel)
                                .addComponent(projectNameLabel)
                                .addGroup(bottomPanelLayout.createSequentialGroup()
                                    .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(startDateLabel)
                                        .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(endDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(endDateLabel)))
                                .addComponent(statusLabel)
                                .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(categoriesLabel)))
                        .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoLabel2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
    );
    bottomPanelLayout.setVerticalGroup(
        bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(bottomPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(projectNameLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(shortDescLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(shortDescTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(genDescLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(genDescScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(statusLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(bottomPanelLayout.createSequentialGroup()
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(categoriesLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(categoryScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(locationLabel)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(locationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(logoLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
            .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(startDateLabel)
                .addComponent(endDateLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(endDateTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(startDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(scopeLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(scopeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(outcomeLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(outcomeScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
            .addContainerGap())
    );

    javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
    mainPanel.setLayout(mainPanelLayout);
    mainPanelLayout.setHorizontalGroup(
        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    mainPanelLayout.setVerticalGroup(
        mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(mainPanelLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    mainScrollPane.setViewportView(mainPanel);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainScrollPane)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(mainScrollPane)
    );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseProjectComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseProjectComboBoxActionPerformed
        // TODO add your handling code here:
        //String selectedProjectId = chooseProjectComboBox.getSelectedItem().toString();
        
        Object projectIdItem = chooseProjectComboBox.getSelectedItem();
        String projectIdValue = ((ComboItem) projectIdItem).getValue();
        List<Project> projList = viewGeneralProjectInformationController.fetchProjectGeneralInformation(projectIdValue);
        projectNameTextField.setText(projList.get(0).getName());
        shortDescTextField.setText(projList.get(0).getShortdesc());
        genDescTextArea.setText(projList.get(0).getDescription());
        if (projList.get(0).getStartDate() != null) {
            startDateTextField.setText(projList.get(0).getStartDate().toString());
        }
        if (projList.get(0).getEndDate() != null) {
            endDateTextField.setText(projList.get(0).getEndDate().toString());
        }
        scopeTextField.setText(projList.get(0).getScope());
        outcomeTextArea.setText(projList.get(0).getOutcome());
        Set<ProjectStatus> set = projList.get(0).getProjectStatusSet();
        for (ProjectStatus projectStatus : set) {
            statusTextField.setText(projectStatus.getStatus());
        }
        Set<ProjectCategory> categorySet = projList.get(0).getProjectCategories();
        String categoryText = "";
        for (ProjectCategory projectCategory : categorySet) {
            categoryText = categoryText + projectCategory.getName() + "\n";
            
        }
        categoryTextArea.setText(categoryText);
    }//GEN-LAST:event_chooseProjectComboBoxActionPerformed

    private void projectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectNameTextFieldActionPerformed

    private void shortDescTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shortDescTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shortDescTextFieldActionPerformed

    private void statusTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTextFieldActionPerformed

    private void locationTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTextFieldActionPerformed

    private void startDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateTextFieldActionPerformed

    private void scopeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scopeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scopeTextFieldActionPerformed

    private void endDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JScrollPane categoryScrollPane;
    private javax.swing.JTextArea categoryTextArea;
    private javax.swing.JComboBox chooseProjectComboBox;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JTextField endDateTextField;
    private javax.swing.JLabel genDescLabel;
    private javax.swing.JScrollPane genDescScrollPane;
    private javax.swing.JTextArea genDescTextArea;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JTextField locationTextField;
    private javax.swing.JLabel logoLabel2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JLabel outcomeLabel;
    private javax.swing.JScrollPane outcomeScrollPane;
    private javax.swing.JTextArea outcomeTextArea;
    private javax.swing.JLabel projectNameLabel;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JLabel scopeLabel;
    private javax.swing.JTextField scopeTextField;
    private javax.swing.JLabel shortDescLabel;
    private javax.swing.JTextField shortDescTextField;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField startDateTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel viewGenProjInfoLabel;
    // End of variables declaration//GEN-END:variables
}
